### ISSUE TITLE
Favicon support

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#123]
Need to be able to add a favicon.ico to the assets folder and have it just work.

**Comment by jsonmaur** [comment]
Adding a file to the static folder will output it at the root of the build, making it accessible at `/favicon.ico`. Is that enough support, or should we go beyond that and add meta tags for it?

**Comment by jsonmaur** [comment]
Closing for now, since this basic functionality is supported by default. Let's reopen in the future if we want to add meta tags for it.
