### ISSUE TITLE
Allow for disabling the right hand side contents

### ISSUE THREAD

**Issue by carkmorwin** [timberio/gitdocs#138]
I was trying to emphasize a piece of the documentation via `#`'s and this renders a contents section which is not useful to the user. Being able to toggle this would be helpful.

![](https://cl.ly/3Q0k411s2q1q/Image%202018-06-01%20at%2009.34.54.png)

**Comment by jsonmaur** [comment]
I agree it should be configurable on a per page basis. But I also think the TOC should only show h1's or maybe h2's as well (`#` or `##`).
