### ISSUE TITLE
Ability to explicitly hide published docs from the nav

### ISSUE THREAD

**Issue by binarylogic** [timberio/gitdocs#151]
Currently in order to hide an item from the nav we must provide `draft: true` in the front-matter. We need something more explicit for documents that are not in a `draft` state, such as `hide-in-nav: true`.

**Comment by jsonmaur** [comment]
So really just an alias for `draft`? Seeing as the end result is the same.

Another way is to define `items` in the front matter, which completely overrides the sidebar items for that file's children. You could do this and intentionally leave something out:

```yaml
items:
  - page-one.md
  - page-two.md
  - page-four.md
```

**Comment by binarylogic** [comment]
My concern with `draft` is that it represents a state that the document is not currently in. In the future if we decide to do anything else with drafts then we'll have unintended side-effects. For example, I'd argue that draft documents shouldn't be available at all in the public published version, they're in a draft state.

**Comment by jsonmaur** [comment]
So maybe `draft` makes the file show up when running the local server but not when deployed. And `hidden: true` will keep the file and route, but hide it in the navigation. I'm good with that.

**Comment by binarylogic** [comment]
👍 sounds good to me
