### ISSUE TITLE
Only include necessary libraries during build

### ISSUE THREAD

**Issue by etimberg** [timberio/gitdocs#41]
When working on #38 I noticed that all possible components are included in the built file. These components are used https://github.com/timberio/gitdocs/blob/master/src/components/Markdown/index.js#L24-L34

As we add new, more complex components, we should either:
* Use code splitting to only load libs when needed
* Only include the react components that are used. If we provide a `<Video>` component, then it should only be included in the bundle if we actually found one from the markdown files

**Comment by jsonmaur** [comment]
Closing this issue, as it pertains to an old version of gitdocs.
