### ISSUE TITLE
Create init command

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#50]
- checks for existing docs and adds a .gitdocs config file if necessary
- if no docs, it generates a docs folder with proper examples/boilerplate

**Comment by jsonmaur** [comment]
@zsherman Since the config file is optional, do you think we should create one when running the init command? The contents would just be `{}` if we did.

**Comment by zsherman** [comment]
I think so, but let’s make sure we can recover if it doesn’t exist.
