### ISSUE TITLE
Reference style links fail to render

### ISSUE THREAD

**Issue by carkmorwin** [timberio/gitdocs#54]
The following link format fails to render as a link, it is only rendered as text. 

```markdown
[Link]

[Link]:google.com
```

**Comment by jsonmaur** [comment]
@carkmorwin The correct way to do reference style links in markdown is
```
[Link Text][Link Reference]

[Link Reference]: google.com
```

**Comment by carkmorwin** [comment]
@jsonmaur Thanks!

I just want to note that this should be included in any docs or info we provide. I think anything that differs from github markdown should be front and center, as our users might be confused/annoyed. 

Example: https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md

**Comment by jsonmaur** [comment]
This should be fixed via https://github.com/timberio/gitdocs/pull/110.
