### ISSUE TITLE
Serve cmd only works when inside docs folder

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#58]
I would expect GitDocs to find the root and use my `/docs` folder instead of having to `cd` in there.

**Comment by jsonmaur** [comment]
Was defaulting to a `docs` folder before, but watched Mark try to use it without any context and he got confused. Defaulting to the cwd as the root is much better. You can always specify a `root` path in your config file. It will also ask you for the root when you run `gitdocs init`.
