### ISSUE TITLE
Refreshing browser on route does not show sidebar tree

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#59]
1. Added a file
2. Restarted my gitdocs server
3. Reloaded the page
4. Sidebar does not reflect folder structure
  - Site: https://cl.ly/3U0r2L2X0J2j
  - Files: https://cl.ly/2z05402P1s1u

**Comment by jsonmaur** [comment]
I believe this is fixed. Reopen if you encounter it again.
