### ISSUE TITLE
Support static sidebar links

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#66]
I have these external URLs I would like to link out to, but don't want to render any documentation for them: https://cl.ly/0a101f1C3C20.

**Comment by jsonmaur** [comment]
You can use `sidebar_links` in the config file for this.
Can also use `header_links` to add links to the header.

Should follow this structure:
```json
"sidebar_links": [
  { "text": "Link Text", "href": "http://url", "target": "_blank" }
]
```

**Comment by zsherman** [comment]
Hm this didn't seem to work for me.

**Comment by jsonmaur** [comment]
Are you running the latest binary?
