### ISSUE TITLE
Build folder should not be prefixed with a "."

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#68]
I don't think the docs output should be prefixed with a dot, it's not a reserved folder it's something you specifically want to deploy.

**Comment by jsonmaur** [comment]
Prefixing with a dot treats it as a hidden folder on unix filesystems. Which makes sense since it's a generated directory and should be ignored/hidden. Have seen several apps that do this. Open to other name suggestions though.

**Comment by tannerlinsley** [comment]
I would call it dist

**Comment by jsonmaur** [comment]
Docs will usually be in a repo alongside the actual code, which will usually have its own build system. So we don't want any folder name conflicts. Need to have `gitdocs` or `docs` in the build directory name.

**Comment by zsherman** [comment]
Do you have examples of projects that prefix the build output with a `.`? I would call it `docs-dist` or `gitdocs-dist` or something.

**Comment by jsonmaur** [comment]
Terraform saves to `.terraform` when downloading modules: https://www.terraform.io/docs/commands/get.html
Also [NYC](https://github.com/istanbuljs/nyc) saves to `.nyc_output` for test coverage data.

I'm fine using `docs_dist` or `docs_build` though. Just won't hide it by default.

**Comment by jsonmaur** [comment]
Come to think of it, we may be downloading temporary data in the future when the sources are implemented (such as cloning git repos), so we may want a `.gitdocs` folder for that similar to how Terraform does it.

**Comment by jsonmaur** [comment]
@zsherman Another argument for using `.gitdocs_build`: Gitdocs will default to building docs from the cwd if no root is specified in the config file. We obviously don't want it to include the output folder when building docs, and since we ignore dotfiles when building, it makes sense to prefix the output folder with a dot.

Just a thought.

**Comment by zsherman** [comment]
hmm, still not convinced on this.

**Comment by jsonmaur** [comment]
I think all the stuff we discussed yesterday pertaining to the `.gitdocs.json` config file applies to this as well. Gitdocs is kind of a "guest" in the project and not part of the main project itself, thus everything it does should stay out of the way. What if a project already has a `docs_build` folder that is unrelated?

**Comment by jsonmaur** [comment]
@binarylogic any input on this?
