### ISSUE TITLE
Support react component rendering

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#9]
Some inspiration:

- https://github.com/gatsbyjs/gatsby/issues/312#issuecomment-336681894
- https://www.npmjs.com/package/reactdown
- https://github.com/gatsbyjs/gatsby/pull/3012
- http://md-to-react.surge.sh/
- https://github.com/fazouane-marouane/remark-jsx/tree/master/packages/remark-custom-element-to-hast

**Comment by yjose** [comment]
a good approach here  https://github.com/probablyup/markdown-to-jsx

**Comment by mrpotatoes** [comment]
@yjose It uses `dangerouslySetInnerHTML` though. Something like remark does not which would be a better option imo.
