### ISSUE TITLE
Add `routes` command that outputs the route structure

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#92]
It would be handy to add a command that outputs the structure of the route tree, either in the terminal or to a `json` file, this would make it easy to visualize the structure or paste into your config to override it.

**Comment by jsonmaur** [comment]
I added a `gitdocs manifest` command in https://github.com/timberio/gitdocs/pull/113, which will output the manifest object for debugging purposes (kept it undocumented in the help menu.)
