### ISSUE TITLE
Output `db.json` file during build

### ISSUE THREAD

**Issue by zsherman** [timberio/gitdocs#93]
This would allow us to add extremely fast client side searching (via lunr or js-search) without the need for an external API in many cases. Obviously this doesn't scale too well for sites with thousands of files but in most cases it should be totally fine.

**Comment by binarylogic** [comment]
I think a better name for this is probably `index.json`, but how do you plan to build this index with respect to removing styling / components / formatting?

**Comment by zsherman** [comment]
This is for search and tokenization, we'll ignore any components or special formatting.

**Comment by jsonmaur** [comment]
Implemented in https://github.com/timberio/gitdocs/pull/116.
