### ISSUE TITLE
Flexible index.md detection

### ISSUE THREAD

**Issue by jsonmaur** [timberio/gitdocs#96]
Currently when detecting the index of a folder, we just look for an `index.md`. But we should also be looking for `README.md`, or a filename that matches the folder (such as using `folder.md` as the index for `folder/file.md`.)

Should we allow all of them by default, or choose one and allow it to be configurable? If supporting all of them at once, we'd need to make sure there are no collisions--such as having `readme.md` and `index.md` in the same folder, or having both `folder.md` and `folder/index.md`.

**Comment by binarylogic** [comment]
👍 on this. I think we should detect all variations, but throw an error during the build process when there is a conflict. More specifically:

- `configuration.md` -> `/configuration`
- `configuration/index.md` -> `/configuration`
- `configuration.md` and `configuration/some_other_file.md` -> `/configuration` and `/configuration/some_other_file`
- `configuration/index.md` and `configuration/some_other_file.md` -> `/configuration` and `/configuration/some_other_file`
- `configuration.md` and `configuration/index.md` -> **throw error**

**Comment by jsonmaur** [comment]
It makes sense to support both `index.md` and `readme.md`, though not sold on the idea of supporting `folder.md` as the index for `folder/`. It's not straightforward what it's doing, and if [the filesystem is always the source of truth for sidebar structure](https://github.com/timberio/gitdocs/issues/106#issuecomment-389632100), we shouldn't be moving things around behind the scenes.

**Comment by jsonmaur** [comment]
Implemented in https://github.com/timberio/gitdocs/pull/113.
