### ISSUE TITLE
Custom ordering of sidebar links

### ISSUE THREAD

**Issue by jsonmaur** [timberio/gitdocs#97]
Leaving a paper trail of our in-person discussions on this so we don't forget. We decided to go with changing the nav tree structure in the manifest from an array of objects to a dictionary with the url as the key, and `title: ' '`/`children: {}` as the values. We can then do a deep merge on the custom nav tree provided in the config with the nav tree generated by GitDocs (based on the filesystem) without having to worry about conflicts. This makes it so you don't have to redefine everything in your sidebar to customize the order of a few things.

Still don't feel great about this as it's weird to define a bunch of empty objects:
```json
{
  "/node": {
    "children": {
      "/installation": {},
      "/usage": {},
      "/loggers": {},
    }
  }
}
```

Maybe we should allow an array of urls as the children and convert it to the correct object behind the scenes? Also not loving the idea of being able to overwrite front matter (such as a custom title) in here. I feel like it should only be configurable from one place, otherwise it gets messy and could lead to confusion--especially in a large docs site.

**Comment by jsonmaur** [comment]
Also if we're doing a deep merge with a custom and default sidebars, we should allow a `mergeSidebar: Boolean` config option.

**Comment by binarylogic** [comment]
I don't have full context on this discussion, but I agree that the empty objects are awkward. The other thing I would note, if the navigation can be custom ordered it should use a structure that preserves ordering, such as an array.

**Comment by jsonmaur** [comment]
Moving discussion to https://github.com/timberio/gitdocs/issues/106.
